# Generated by Django 5.0.6 on 2024-06-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonrecord',
            name='problem_statement',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonrecord',
            name='tag',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonrecord',
            name='tech',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
